import { Helmet } from "react-helmet-async";
import { motion } from "framer-motion";

export default function PrivacyPolicy() {
  return (
    <div className="w-full max-w-4xl mx-auto px-4 py-32">
      <Helmet>
        <title>Privacy Policy | LumoUX Design Studio</title>
      </Helmet>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-zinc-800 dark:text-zinc-200 space-y-6">
        <h1 className="text-4xl font-bold text-zinc-900 dark:text-white mb-8">Privacy Policy</h1>
        <p className="text-sm text-zinc-500 dark:text-zinc-400">Last updated: February 07, 2026</p>

        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Interpretation and Definitions</h2>
        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Interpretation</h3>
        <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to lumoux.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Romania</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>Website</strong> refers to lumoux, accessible from <a href="https://www.lumouxdesign.eu" className="text-purple-600 dark:text-purple-400 hover:underline">www.lumouxdesign.eu</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Types of Data Collected</h3>
        
        <h4 className="text-lg font-medium text-zinc-900 dark:text-white mt-4 mb-2">Personal Data</h4>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li><strong>Contact Information:</strong> When you use our contact form, we collect your name, email address, phone number, and the contents of your message. This data is securely stored and used solely to respond to your inquiries and provide the requested services.</li>
          <li><strong>Usage Data:</strong> Information automatically collected about your interaction with the Service.</li>
        </ul>

        <h4 className="text-lg font-medium text-zinc-900 dark:text-white mt-4 mb-2">Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

        <h4 className="text-lg font-medium text-zinc-900 dark:text-white mt-4 mb-2">Tracking Technologies and Cookies</h4>
        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
        
        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
          <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        </ul>

        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Retention of Your Personal Data</h3>
        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Transfer of Your Personal Data</h3>
        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>

        <h3 className="text-xl font-medium text-zinc-900 dark:text-white mt-6 mb-3">Delete Your Personal Data</h3>
        <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by contacting Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Security of Your Personal Data</h2>
        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Changes to this Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>

        <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mt-8 mb-4">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>By email: <a href="mailto:rhadooss83@gmail.com" className="text-purple-600 dark:text-purple-400 hover:underline">rhadooss83@gmail.com</a></li>
        </ul>
      </motion.div>
    </div>
  );
}
